# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'VFix_Expert' do

    pod 'TPDMapsApp', '~> 1.0'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'Cosmos', '~> 1.2'
    pod 'Alamofire'
    
    pod 'CalendarLib', '~> 1.0'
    pod 'OSCache', '~> 1.2'
    pod 'OrderedDictionary', '~> 1.2'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

